//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_SQL_LINQ_Hotel_Booking_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillingID { get; set; }
        public int GuestIDFK { get; set; }
        public Nullable<decimal> BarCharge { get; set; }
        public Nullable<decimal> wifiCharge { get; set; }
        public Nullable<decimal> PhoneCharge { get; set; }
        public Nullable<decimal> RoomCharge { get; set; }
        public decimal TotalCharge { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
