//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_SQL_LINQ_Hotel_Booking_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int GuestID { get; set; }
        public Nullable<int> BooklingIDFK { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> ContactNumber { get; set; }
        public Nullable<int> NumberOfGuests { get; set; }
        public Nullable<int> RoomBooked { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<System.DateTime> BooklingDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Meals { get; set; }
        public Nullable<int> Activities { get; set; }
        public Nullable<int> Vehiclals { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Booking Booking { get; set; }
    }
}
