//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_SQL_LINQ_Hotel_Booking_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int RoomID { get; set; }
        public int SingleBeds_ { get; set; }
        public int DoubleBeds_ { get; set; }
        public string ExtraFeatures { get; set; }
        public decimal SinglePerson { get; set; }
        public Nullable<decimal> C2People { get; set; }
        public Nullable<decimal> ExtraPeople { get; set; }
        public Nullable<System.DateTime> DateBookedFrom { get; set; }
        public Nullable<System.DateTime> DateBookedTill { get; set; }
        public Nullable<int> RoomCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
